---

dist: focal

language: python
sudo: required

env:
  - ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3

install:
  - sudo add-apt-repository universe
  - sudo apt-get update

  # Install ansible
  - pip install -U ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - "ansible-playbook tests/test.yml -i tests/inventory --connection=local"
  - "ansible-playbook tests/test.yml -i tests/inventory --connection=local"

  - /usr/sbin/nginx -V
  - ls -lh /usr/lib/nginx/modules

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
