---

dist: focal
language: minimal

env:
  - ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3

# Install ansible
addons:
  apt:
    packages:
      - ansible
      - ansible-lint

install:
  - sudo add-apt-repository universe
  - sudo apt-get update

  # Check ansible versions
  - ansible --version
  - ansible-lint --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - ansible-lint
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local
  - ls -lh /usr/share/nginx/modules
  - sudo /usr/sbin/nginx -T
  - /usr/sbin/nginx -V

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
