---

- name: Create folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    recurse: no
  with_items:
    - /etc/nginx
    - /var/cache/nginx
    - /etc/nginx/common
    - /etc/nginx/vhosts
  become: yes

- name: Add logrotate config
  ansible.builtin.copy:
    src: logrotate
    dest: /etc/logrotate.d/nginx
    mode: 0644
  become: yes

- name: Add systemd service
  ansible.builtin.copy:
    src: nginx.service.ini
    dest: /lib/systemd/system/nginx.service
    mode: 0644
  become: yes
  notify:
    - reload_systemd
    - restart_nginx

- name: Add htpasswd script
  ansible.builtin.copy:
    src: htpasswd.sh
    dest: /usr/local/bin/htpasswd
    mode: a+x
  become: yes

- name: Adding base config files
  ansible.builtin.copy:
    force: yes
    src: "{{ item }}"
    dest: /etc/nginx/{{ item }}
    mode: 0644
  with_items:
    - common/client-performance.conf
    - common/client-performance-inline.conf
    - common/cloudflare.conf
    - common/drop.conf
    - common/fix-slashes.conf
    - common/munin-node.conf
    - common/secure-ssl.conf
    - fastcgi.conf
    - mime.types
  become: yes
  notify: restart_nginx

- name: Add nginx.conf
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: 0644
  become: yes
  notify: restart_nginx

- name: Add default vhost config
  ansible.builtin.copy:
    force: no
    src: vhost.conf
    dest: /etc/nginx/vhosts/default.conf
    mode: 0644
  become: yes
