---

- name: create folders
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    recurse: no
  with_items:
    - /etc/nginx
    - /var/cache/nginx
    - /etc/nginx/common
    - /etc/nginx/vhosts
  become: yes

- name: add logrotate config
  copy:
    src: logrotate
    dest: /etc/logrotate.d/nginx
  become: yes

- name: check for systemd
  command: systemctl --version
  register: systemctl_version
  ignore_errors: yes

- name: add systemd service
  copy:
    src: nginx.service.ini
    dest: /lib/systemd/system/nginx.service mode=0644
  become: yes
  when: systemctl_version.rc == 0
  notify: restart_nginx

- name: reload systemd
  command: systemctl daemon-reload
  when: systemctl_version.rc == 0
  become: yes

- name: add sysvinit service
  copy:
    src: init.sh
    dest: /etc/init.d/nginx
    mode: "a+x"
  become: yes
  when: systemctl_version.rc != 0
  notify: restart_nginx

- name: add htpasswd script
  copy:
    src: htpasswd.sh
    dest: /usr/local/bin/htpasswd
    mode: "a+x"
  become: yes

- name: adding base config files
  copy:
    force: yes
    src: "{{ item }}"
    dest: /etc/nginx/{{ item }}
  with_items:
    - common/client-performance.conf
    - common/client-performance-inline.conf
    - common/cloudflare.conf
    - common/drop.conf
    - common/fix-slashes.conf
    - common/munin-node.conf
    - common/secure-ssl.conf
    - fastcgi.conf
    - mime.types
  become: yes
  notify: restart_nginx

- name: add nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  become: yes
  notify: restart_nginx

- name: add default vhost config
  copy:
    force: no
    src: vhost.conf
    dest: /etc/nginx/vhosts/default.conf
  become: yes
  notify: restart_nginx
