---

- name: install dependencies
  apt:
    name: libwww-perl
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: add nginx_request plugin
  file:
    src: /usr/share/munin/plugins/nginx_request
    dest: /etc/munin/plugins/nginx_request
    state: link
  notify: nginx_restart_munin_node
  become: yes

- name: add nginx_status plugin
  file:
    src: /usr/share/munin/plugins/nginx_status
    dest: /etc/munin/plugins/nginx_status
    state: link
  notify: nginx_restart_munin_node
  become: yes

- name: add munin plugin-conf
  copy:
    content: |
      [nginx*]
      env.url http://127.0.8.9/nginx_status
    dest: /etc/munin/plugin-conf.d/nginx_
    mode: 0644
  notify: nginx_restart_munin_node
  become: yes
