---

- name: Install dependencies
  ansible.builtin.apt:
    name: libwww-perl
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Add nginx_request plugin
  ansible.builtin.file:
    src: /usr/share/munin/plugins/nginx_request
    dest: /etc/munin/plugins/nginx_request
    state: link
  notify: Restart_munin_node
  become: true

- name: Add nginx_status plugin
  ansible.builtin.file:
    src: /usr/share/munin/plugins/nginx_status
    dest: /etc/munin/plugins/nginx_status
    state: link
  notify: Restart_munin_node
  become: true

- name: Add munin plugin-conf
  ansible.builtin.copy:
    content: |
      [nginx*]
      env.url http://127.0.8.9/nginx_status
    dest: /etc/munin/plugin-conf.d/nginx_
    mode: '0644'
  notify: Restart_munin_node
  become: true
