---
- name: Install dependencies
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - libwww-perl
  become: yes

- name: Add nginx_request plugin
  file: src=/usr/share/munin/plugins/nginx_request dest=/etc/munin/plugins/nginx_request state=link
  notify: restart_munin_node
  become: yes

- name: Add nginx_status plugin
  file: src=/usr/share/munin/plugins/nginx_status dest=/etc/munin/plugins/nginx_status state=link
  notify: restart_munin_node
  become: yes