---

- name: install dependencies
  apt:
    name:
      - make
      - gcc
      - g++
      - unzip
      - libmodsecurity-dev
      - libpcre3-dev
      - zlib1g-dev
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: fetch sources
  unarchive:
    src: "{{ item }}"
    dest: /tmp
    remote_src: yes
  with_items:
    - http://nginx.org/download/nginx-{{ nginx_version }}.tar.gz
    - https://www.openssl.org/source/openssl-{{ openssl_version }}.tar.gz

- name: cleanups
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/ngx_brotli-{{ ngx_brotli_version }}
    - /tmp/headers-more-nginx-module-{{ ngx_headers_more_version }}
    - /tmp/ngx-fancyindex-{{ ngx_fancyindex_version }}
    - /tmp/modsecurity-nginx-v{{ ngx_modsecurity_version }}
    - /tmp/njs-{{ ngx_njs_version }}
  become: yes

- name: download ngx_*
  unarchive:
    src: "{{ item }}"
    dest: /tmp
    remote_src: yes
  with_items:
    - https://github.com/google/ngx_brotli/archive/{{ ngx_brotli_version }}.zip
    - https://github.com/openresty/headers-more-nginx-module/archive/v{{ ngx_headers_more_version }}.zip
    - https://github.com/aperezdc/ngx-fancyindex/archive/v{{ ngx_fancyindex_version }}.tar.gz
    - https://github.com/SpiderLabs/ModSecurity-nginx/releases/download/v{{ ngx_modsecurity_version }}/modsecurity-nginx-v{{ ngx_modsecurity_version }}.tar.gz
    - https://github.com/nginx/njs/archive/refs/tags/{{ ngx_njs_version }}.tar.gz

- name: fetch brotli
  unarchive:
    src: https://github.com/google/brotli/archive/v{{ brotli_version }}.tar.gz
    dest: /tmp/ngx_brotli-{{ ngx_brotli_version }}/deps/
    remote_src: yes

- name: remove brotli folder
  file:
    path: /tmp/ngx_brotli-{{ ngx_brotli_version }}/deps/brotli
    state: absent

- name: rename brotli folder
  command: mv /tmp/ngx_brotli-{{ ngx_brotli_version }}/deps/brotli-{{ brotli_version }} /tmp/ngx_brotli-{{ ngx_brotli_version }}/deps/brotli
  changed_when: yes

- name: make clean
  command: make clean
  args:
    chdir: /tmp/nginx-{{ nginx_version }}
  changed_when: yes
  ignore_errors: yes

- name: configure
  command: >
    ./configure
    --prefix=/usr/share/nginx
    --sbin-path=/usr/sbin/nginx
    --conf-path=/etc/nginx/nginx.conf
    --http-log-path=/var/log/nginx/access.log
    --error-log-path=/var/log/nginx/error.log
    --lock-path=/var/lock/nginx.lock
    --pid-path=/run/nginx.pid
    --http-client-body-temp-path=/var/cache/nginx/client
    --http-proxy-temp-path=/var/cache/nginx/proxy
    --http-fastcgi-temp-path=/var/cache/nginx/fastcgi
    --http-uwsgi-temp-path=/var/cache/nginx/uwsgi
    --http-scgi-temp-path=/var/cache/nginx/scgi
    --without-select_module
    --without-poll_module
    --with-threads
    --with-file-aio
    --with-http_ssl_module
    --with-openssl=../openssl-{{ openssl_version }}
    --with-http_realip_module
    --with-http_stub_status_module
    --with-http_v2_module
    --with-http_gunzip_module
    --with-http_gzip_static_module
    --with-http_auth_request_module
    --with-http_secure_link_module
    --without-http_memcached_module
    --add-module=/tmp/ngx_brotli-{{ ngx_brotli_version }}
    --add-module=/tmp/headers-more-nginx-module-{{ ngx_headers_more_version }}
    --add-dynamic-module=/tmp/ngx-fancyindex-{{ ngx_fancyindex_version }}
    --add-dynamic-module=/tmp/modsecurity-nginx-v{{ ngx_modsecurity_version }}
    --add-dynamic-module=/tmp/njs-{{ ngx_njs_version }}/nginx
  args:
    chdir: /tmp/nginx-{{ nginx_version }}
  changed_when: yes

- name: make
  command: make -j{{ nginx_make_jobs }}
  args:
    chdir: /tmp/nginx-{{ nginx_version }}
  changed_when: yes

- name: install
  command: make install
  args:
    chdir: /tmp/nginx-{{ nginx_version }}
  changed_when: yes
  become: yes
  notify: restart_nginx
