---

- name: install dependencies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
      - make
      - gcc
      - g++
      - unzip
  become: yes

- name: fetch sources
  unarchive:
    src: "{{ item }}"
    dest: /tmp
    remote_src: yes
  with_items:
    - http://nginx.org/download/nginx-{{ nginx_version }}.tar.gz
    - https://ftp.pcre.org/pub/pcre/pcre-{{ pcre_version }}.tar.gz
    - https://www.openssl.org/source/openssl-{{ openssl_version }}.tar.gz
    - http://zlib.net/zlib-{{ zlib_version }}.tar.gz

- name: cleanups
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/ngx_brotli-{{ nginx_brotli_version }}
    - /tmp/headers-more-nginx-module-{{ nginx_headers_more_version }}
  become: yes

- name: clone ngx_brotli
  git:
    repo: https://github.com/google/ngx_brotli.git
    dest: /tmp/ngx_brotli-{{ nginx_brotli_version }}
    accept_hostkey: yes

- name: fetch ngx_headers_more
  unarchive:
    src: https://github.com/openresty/headers-more-nginx-module/archive/v{{ nginx_headers_more_version }}.zip
    dest: /tmp
    remote_src: True

- name: make clean
  command: make clean
  args:
    chdir: /tmp/nginx-{{ nginx_version }}
  ignore_errors: yes

- name: configure
  command: >
    ./configure
    --prefix=/usr/share/nginx
    --sbin-path=/usr/sbin/nginx
    --conf-path=/etc/nginx/nginx.conf
    --http-log-path=/var/log/nginx/access.log
    --error-log-path=/var/log/nginx/error.log
    --lock-path=/var/lock/nginx.lock
    --pid-path=/run/nginx.pid
    --http-client-body-temp-path=/var/cache/nginx/client
    --http-proxy-temp-path=/var/cache/nginx/proxy
    --http-fastcgi-temp-path=/var/cache/nginx/fastcgi
    --http-uwsgi-temp-path=/var/cache/nginx/uwsgi
    --http-scgi-temp-path=/var/cache/nginx/scgi
    --without-select_module
    --without-poll_module
    --with-pcre=../pcre-{{ pcre_version }}
    --with-pcre-jit
    --with-zlib=../zlib-{{ zlib_version }}
    --with-zlib-asm=pentiumpro
    --with-http_ssl_module
    --with-openssl=../openssl-{{ openssl_version }}
    --with-http_addition_module
    --with-http_realip_module
    --with-http_sub_module
    --with-http_flv_module
    --with-http_mp4_module
    --with-http_gunzip_module
    --with-http_gzip_static_module
    --with-http_auth_request_module
    --with-http_random_index_module
    --with-http_secure_link_module
    --with-http_stub_status_module
    --with-http_auth_request_module
    --with-http_stub_status_module
    --with-threads
    --with-file-aio
    --with-http_v2_module
    --with-ipv6
    --without-http_memcached_module
    --add-module=/tmp/ngx_brotli-{{ nginx_brotli_version }}
    --add-module=/tmp/headers-more-nginx-module-{{ nginx_headers_more_version }}
  args:
    chdir: /tmp/nginx-{{ nginx_version }}

# removing temporarily -j{{ ansible_processor_vcpus }} due to: https://github.com/openssl/openssl/issues/7679
- name: make
  command: make
  args:
    chdir: /tmp/nginx-{{ nginx_version }}

- name: install
  command: make install
  args:
    chdir: /tmp/nginx-{{ nginx_version }} 
  become: yes
  notify: restart_nginx
