---

version: 2.1

jobs:

  build:
    machine:
      # https://circleci.com/docs/configuration-reference#available-linux-machine-images
      image: ubuntu-2204:2022.04.1
    environment:
      ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3

    steps:
      - run: sudo rm -f /etc/apt/sources.list.d/google.list /etc/apt/sources.list.d/heroku.list
      - run: sudo apt-get update
      - run: sudo apt remove --assume-yes --purge apparmor
      - run: sudo apt install --assume-yes net-tools
      - run: pip3 install ansible ansible-lint

      - run: ansible --version
      - run: ansible-lint --version

      - checkout

      - run: printf '[defaults]\nroles_path=../' > ansible.cfg
      - run: ansible-lint

      - run: ansible-playbook tests/test.yml -i tests/inventory --connection=local

      - run:
          command: sudo journalctl --no-pager --unit=nginx
          when: on_fail
      - run:
          command: sudo cat /var/log/nginx/error.log
          when: on_fail

      - run: ansible-playbook tests/test.yml -i tests/inventory --connection=local

      - run: ls -lh /usr/share/nginx/modules
      - run: sudo /usr/sbin/nginx -T
      - run: /usr/sbin/nginx -V
