---

- name: Reload_systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes

- name: Restart_nginx
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: restarted
  become: yes

- name: Restart_munin_node
  ansible.builtin.systemd:
    name: munin-node
    state: restarted
  become: yes

- name: Restart_fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
  become: yes
