---

- name: restart_nginx
  service: name=nginx enabled=yes state=restarted
  become: yes

- name: restart_munin_node
  service: name=munin-node state=restarted
  become: yes

- name: restart_fail2ban
  service: name=fail2ban state=restarted
  become: yes
