---

- name: restart_nginx
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: restarted
  become: yes

- name: nginx_systemd_reload
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes

- name: nginx_restart_munin_node
  ansible.builtin.systemd:
    name: munin-node
    state: restarted
  become: yes

- name: nginx_restart_fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
  become: yes
